import LittleCMSCore
import Testing

/// The parametric evaluator, against values the reference actually
/// produced.  The fixture beside this file is generated by
/// scripts/gen_curve_fixture.sh from a reference build; when the curve
/// object lands, a differential program replaces it and this becomes
/// redundant.
@Suite
struct ParametricCurveTests {
    /// The reference reaches the evaluator through a curve whose one
    /// segment spans ±1e22, so what comes back is the evaluator's value
    /// with an infinity clamped to that constant and the result narrowed
    /// to float.  Both are applied here rather than hidden in the engine,
    /// because both belong to the curve rather than to the evaluator.
    static func asTheReferenceReportsIt(_ value: Double) -> Float {
        if value.isInfinite { return Float(value > 0 ? 1e22 : -1e22) }
        return Float(value)
    }

    @Test
    func everyTypeMatchesTheReference() {
        var checked = 0

        for row in parametricExpectations {
            let produced = row.params.withUnsafeBufferPointer { params in
                ParametricCurve.evaluate(type: row.type, params: params.baseAddress!, at: row.input)
            }

            let ours = Self.asTheReferenceReportsIt(produced)
            let theirs = Float(row.output)

            // NaN is a legitimate answer for an inverse outside its
            // domain, and two NaNs are equal for this purpose.
            if ours.isNaN && theirs.isNaN { checked += 1; continue }

            #expect(
                ours == theirs,
                "type \(row.type) params \(row.params) at \(row.input): \(ours) vs \(theirs)"
            )
            checked += 1
        }

        #expect(checked == parametricExpectations.count)
        #expect(checked > 400, "the fixture should cover every type across its range")
    }

    @Test
    func theParameterCountsAreTheRegistrys() {
        // The reference's built-in table: types 1,2,3,4,5,6,7,8,108,109
        // taking 1,3,4,5,7,4,5,5,1,1 parameters.
        let expected: [Int32: Int] = [
            1: 1, 2: 3, 3: 4, 4: 5, 5: 7, 6: 4, 7: 5, 8: 5, 108: 1, 109: 1,
        ]
        for (type, count) in expected {
            #expect(ParametricCurve.parameterCount(forType: type) == count)
            // A negative type is the same curve inverted, so it takes the
            // same parameters.
            #expect(ParametricCurve.parameterCount(forType: -type) == count)
        }
        #expect(ParametricCurve.parameterCount(forType: 42) == nil)
        #expect(ParametricCurve.supportedTypes.count == expected.count)
    }

    @Test
    func anUnsupportedTypeEvaluatesToZero() {
        var params = [1.0]
        let value = params.withUnsafeMutableBufferPointer { p in
            ParametricCurve.evaluate(type: 42, params: p.baseAddress!, at: 0.5)
        }
        #expect(value == 0)
    }
}
