#!/usr/bin/env python3
"""Generate a stub for every exported symbol not yet implemented.

The library is a loadable drop-in from the first buildable commit: every
one of the 382 exported functions resolves, and every call to one that is
not implemented yet fails loudly instead of returning a plausible wrong
answer.

Body policy:
  - The signature carries a `cmsContext` parameter: report through the
    library's normal error path (the context's logger) and return zero —
    the reference's own convention for graceful failure.
  - No `cmsContext` anywhere: swift_unimplemented_fatal, which prints to
    stderr and aborts.  With no reporting channel, a silent zero from,
    say, cmsD50_XYZ would be a wrong answer rather than a failure.
  - A variadic in the stub set is a generator error: variadics cannot be
    generated (or written in Swift) and live permanently in
    lcms2_variadic.c and scripts/implemented.txt.

Input:  scripts/api.json (from gen_api.py), scripts/implemented.txt
Output: Sources/CLCMS2/gen/lcms2_stubs.c (committed;
        scripts/check_generated.sh keeps it honest)
"""

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "Sources" / "CLCMS2" / "gen" / "lcms2_stubs.c"

HEADER = """\
/* Generated by scripts/gen_stubs.py — do not edit.
 *
 * One stub per exported symbol with no real definition yet, so the shared
 * library always exports the complete lcms2 surface and fails loudly on
 * every call into the unimplemented part.  Retire a stub by adding its
 * name to scripts/implemented.txt and regenerating; a name retired without
 * being listed there is a duplicate symbol at link time.
 */

#include "swift_internal.h"

"""

CONTEXT_PARAMETER = re.compile(r"(?:^|[(,])\s*cmsContext\s+([A-Za-z_][A-Za-z0-9_]*)\s*(?=[,)]|$)")


def stub(record: dict) -> str:
    name = record["name"]
    returns = record["return"]
    parameters = record["parameters"]
    lines = [f"{returns} {name}({parameters})", "{"]
    context = CONTEXT_PARAMETER.search(parameters)
    if context:
        lines.append(
            f'    swift_c_signal_error({context.group(1)}, cmsERROR_NOT_SUITABLE, "{name} is not implemented");'
        )
        if returns != "void":
            lines.append(f"    return ({returns}){{0}};")
    else:
        lines.append(f'    swift_unimplemented_fatal("{name}");')
    lines.append("}")
    return "\n".join(lines)


def main() -> None:
    api = json.loads((REPO / "scripts" / "api.json").read_text())
    implemented = {
        line.strip()
        for line in (REPO / "scripts" / "implemented.txt").read_text().splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }

    names = {record["name"] for record in api}
    unknown = sorted(implemented - names)
    if unknown:
        sys.exit(f"gen_stubs: implemented.txt lists names that are not exported: {unknown}")

    stubs = [record for record in api if record["name"] not in implemented]
    variadic = sorted(record["name"] for record in stubs if record["variadic"])
    if variadic:
        sys.exit(
            f"gen_stubs: variadic functions cannot be stubbed, implement them in C: {variadic}"
        )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(HEADER + "\n\n".join(stub(record) for record in stubs) + "\n")
    print(f"gen_stubs: {len(stubs)} stubs ({len(implemented)} implemented)")


if __name__ == "__main__":
    main()
