#!/usr/bin/env python3
"""Expose the TYPE_* pixel-format constants to Swift.

Every TYPE_* in lcms2.h is a macro *expression* -- a fold of the
COLORSPACE_SH/CHANNELS_SH/BYTES_SH shifts -- so Swift cannot import it.
Only C can evaluate them, which leaves two options: transcribe 178 values
by hand, or have the compiler do it.

This does the second. It reads the names out of the vendored header and
emits one constant per name, initialised from the macro itself, so a
value can never disagree with the header it came from. The names are the
only thing this script transcribes, and a name it gets wrong fails to
compile rather than silently naming the wrong layout.

usage: gen_pixel_types.py [--check]
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HEADER = ROOT / "Sources/CLCMS2/include/lcms2.h"
OUTPUT = ROOT / "Sources/CLCMS2/include/lcms2_pixel_types.h"

BANNER = """/* lcms2_pixel_types.h - GENERATED by scripts/gen_pixel_types.py, do not edit
 *
 * The TYPE_* constants as values Swift can see.  Each is initialised from
 * the macro of the same name in lcms2.h, so the compiler computes it and
 * this file cannot drift from the header.
 *
 * Named with a prefix because these are ours, not part of the ABI: they
 * are never exported, and no client ever sees them.
 */

#ifndef SLCMS_PIXEL_TYPES_H
#define SLCMS_PIXEL_TYPES_H

#include "lcms2.h"

"""

FOOTER = """
#endif /* SLCMS_PIXEL_TYPES_H */
"""


def collect(header: pathlib.Path) -> list[str]:
    names: list[str] = []
    seen: set[str] = set()
    pattern = re.compile(r"^#\s*define\s+(TYPE_[A-Za-z0-9_]+)\s")
    for line in header.read_text().splitlines():
        match = pattern.match(line)
        if match and match.group(1) not in seen:
            seen.add(match.group(1))
            names.append(match.group(1))
    return names


def render(names: list[str]) -> str:
    body = "".join(
        f"static const cmsUInt32Number SLCMS_{name} = {name};\n" for name in names
    )
    return BANNER + body + FOOTER


def main() -> int:
    names = collect(HEADER)
    if not names:
        print("gen_pixel_types: found no TYPE_* definitions", file=sys.stderr)
        return 1

    rendered = render(names)
    if "--check" in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != rendered:
            print(
                "gen_pixel_types: lcms2_pixel_types.h is stale; rerun "
                "scripts/gen_pixel_types.py",
                file=sys.stderr,
            )
            return 1
        print(f"gen_pixel_types: {len(names)} constants are current")
        return 0

    OUTPUT.write_text(rendered)
    print(f"gen_pixel_types: wrote {len(names)} constants")
    return 0


if __name__ == "__main__":
    sys.exit(main())
