#!/usr/bin/env python3
"""Transcribe the half-float conversion tables from the reference.

cmshalf.c converts through five lookup tables rather than by arithmetic,
and the exact contents are the contract: the tables encode how the
reference rounds, including at the subnormal and NaN boundaries where a
hardware conversion (or Swift's Float16) rounds differently.  Transcribing
them by hand is not something to trust, so it is done mechanically, and
the exhaustive round-trip in the conformance suite proves the result.

usage: gen_half_tables.py <path-to-upstream-cmshalf.c>
       (a Little-CMS checkout at tag lcms2.19)

Output: Sources/LittleCMS/Primitives/HalfTables.swift (committed)
"""

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUTPUT = REPO / "Sources" / "LittleCMS" / "Primitives" / "HalfTables.swift"

# name -> (C type, expected length, Swift element type)
TABLES = {
    "Mantissa": ("cmsUInt32Number", 2048, "UInt32"),
    "Offset": ("cmsUInt16Number", 64, "UInt16"),
    "Exponent": ("cmsUInt32Number", 64, "UInt32"),
    "Base": ("cmsUInt16Number", 512, "UInt16"),
    "Shift": ("cmsUInt8Number", 512, "UInt8"),
}

HEADER = """\
// Generated by scripts/gen_half_tables.py from the reference cmshalf.c — do not edit.
//
// The half-float conversions go through these tables rather than through
// arithmetic, because the tables are what defines the reference's rounding
// at the subnormal and NaN boundaries.  Swift's own Float16 conversions
// disagree there, which is why they are not used.

"""


def extract(source: str, name: str, ctype: str, count: int) -> list[int]:
    match = re.search(
        rf"static\s+const\s+{ctype}\s+{name}\s*\[\s*\d*\s*\]\s*=\s*\{{(.*?)\}}\s*;",
        source,
        re.S,
    )
    if not match:
        sys.exit(f"gen_half_tables: table {name} not found")
    values = [int(v, 0) for v in re.findall(r"0x[0-9a-fA-F]+|\d+", match.group(1))]
    if len(values) != count:
        sys.exit(f"gen_half_tables: {name} has {len(values)} entries, expected {count}")
    return values


def emit(name: str, element: str, values: list[int], per_line: int) -> str:
    lines = [f"let half{name}: [{element}] = ["]
    for start in range(0, len(values), per_line):
        chunk = values[start : start + per_line]
        lines.append("    " + ", ".join(f"0x{v:X}" for v in chunk) + ",")
    lines.append("]")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    source = Path(sys.argv[1]).read_text()

    parts = [HEADER]
    for name, (ctype, count, element) in TABLES.items():
        values = extract(source, name, ctype, count)
        per_line = 6 if element == "UInt32" else 12
        parts.append(emit(name, element, values, per_line))
        parts.append("")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(parts))
    print(f"gen_half_tables: wrote {OUTPUT}")


if __name__ == "__main__":
    main()
